name: icp-cli Build

on:
  push:
    branches: [ main ]
    paths:
      - 'icp-cli/**'
      - '.github/workflows/icp-cli-build.yml'
  pull_request:
    paths:
      - 'icp-cli/**'
      - '.github/workflows/icp-cli-build.yml'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build and Test
        run: ./gradlew --no-daemon clean build coverageReport
        working-directory: icp-cli

      - name: Collect Tests Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@v5
        with:
          name: tests-result
          path: icp-cli/build/reports/tests

      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v5
        with:
          files: icp-cli/build/reports/jacoco/coverageReport/coverageReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}
